# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "pulpo-messaging"
email:
description: "lightweight framework for handling distributed delayed job processing. This can be useful for any background jobs that you need within your system"

# Analytics
analytics:
  provider               : google-gtag # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-B941W3153Q
    anonymize_ip         : # true, false (default)

  
twitter_username: jayraynet
github_username: jasonray
# preview of skins: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: EDT # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

breadcrumbs: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag


author:
  name   : "Mighty Pulpo"
  avatar : "/assets/images/greybeard.png"
  bio    : "sometimes brilliant often a slacker... living the life of a burned out hacker"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.jayray.net/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jasonray"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.jayray.net/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jasonray"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
